import { NextRequest, NextResponse } from "next/server"
import { createServerClient } from "@supabase/ssr"
import { GitHubClient } from "@/lib/git/github-client"
import { AzureDevOpsClient } from "@/lib/git/azure-client"

export async function POST(request: NextRequest, { params }: { params: { id: string } }) {
  console.log(` ========== APPLY TASK FIX ==========`)
  console.log(` Task ID: ${params.id}`)

  try {
    const body = await request.json()
    const { method, user_id } = body // method: 'pull_request' | 'direct_commit' | 'copy'

    console.log(` Apply method: ${method}`)
    console.log(` User ID: ${user_id}`)

    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!,
      {
        cookies: {
          get: (name) => request.cookies.get(name)?.value,
          set: () => {},
          remove: () => {},
        },
      }
    )

    const { data: user } = await supabase.from("users").select("role, client_id").eq("id", user_id).single()

    if (!user) {
      return NextResponse.json({ error: "User not found" }, { status: 404 })
    }

    if (method === "direct_commit" && user.role !== "admin" && user.role !== "super_admin") {
      console.error(" Permission denied: User cannot do direct commits")
      return NextResponse.json({ error: "Only administrators can perform direct commits" }, { status: 403 })
    }

    const { data: task } = await supabase
      .from("tasks")
      .select(`
        *,
        repository:repositories(*),
        client:clients(*)
      `)
      .eq("id", params.id)
      .single()

    if (!task) {
      return NextResponse.json({ error: "Task not found" }, { status: 404 })
    }

    console.log(" Task:", task.title)
    console.log(" Repository:", task.repository.full_name)
    console.log(" Provider:", task.repository.provider)

    const { data: token } = await supabase
      .from("github_tokens")
      .select("*")
      .eq("client_id", user.client_id)
      .eq("provider", task.repository.provider)
      .single()

    if (!token) {
      return NextResponse.json(
        { error: `No ${task.repository.provider} token found for this client` },
        { status: 400 }
      )
    }

    console.log(" Git token found for provider:", token.provider)

    if (method === "copy") {
      console.log(" Copy method - returning code")
      return NextResponse.json({
        success: true,
        method: "copy",
        code: task.code_suggested,
      })
    }

    let prNumber: number | undefined
    let prUrl: string | undefined
    let branchName: string | undefined
    let commitSha: string | undefined

    const timestamp = Date.now()
    branchName = `fix/cnpj-line-${task.line_number}-${timestamp}`

    const repoFullName = task.repository.full_name || task.repository.name
    const [owner, repo] = repoFullName.split("/")

    console.log(" Repository owner:", owner)
    console.log(" Repository name:", repo)

    console.log(" Reading file content...")
    let fileContent: string

    if (task.repository.provider === "github") {
      const github = new GitHubClient({
        token: token.access_token,
        owner,
        repo,
      })

      const { content } = await github.getFileContent(task.file_path)
      fileContent = content

      console.log(" Applying code change...")
      const lines = fileContent.split("\n")
      const lineIndex = task.line_number - 1

      if (lineIndex < 0 || lineIndex >= lines.length) {
        throw new Error(`Line number ${task.line_number} is out of bounds`)
      }

      lines[lineIndex] = task.code_suggested
      const newContent = lines.join("\n")

      await github.createBranch({ branchName })

      commitSha = await github.createCommit({
        branch: branchName,
        filePath: task.file_path,
        content: newContent,
        message: `fix: ${task.title}\n\nUpdates CNPJ format on line ${task.line_number} to alphanumeric 18-character format.`,
      })

      if (method === "pull_request") {
        const prBody = `## Auto-generated fix for CNPJ format\n\n**Task:** ${task.title}\n**File:** \`${task.file_path}\`\n**Line:** ${task.line_number}\n\n### Changes\n\n\`\`\`diff\n- ${task.code_current}\n+ ${task.code_suggested}\n\`\`\`\n\n---\n\nThis PR was automatically generated by the CNPJ Analysis System.`

        const pr = await github.createPullRequest({
          title: `Fix: ${task.title}`,
          body: prBody,
          head: branchName,
          base: "main",
        })

        prNumber = pr.number
        prUrl = pr.url
      }
    } else if (task.repository.provider === "azure") {
      const [organization, project] = owner.split(".")
      const azure = new AzureDevOpsClient({
        token: token.access_token,
        organization,
        project,
        repository: repo,
      })

      fileContent = await azure.getFileContent(task.file_path)

      console.log(" Applying code change...")
      const lines = fileContent.split("\n")
      const lineIndex = task.line_number - 1

      if (lineIndex < 0 || lineIndex >= lines.length) {
        throw new Error(`Line number ${task.line_number} is out of bounds`)
      }

      lines[lineIndex] = task.code_suggested
      const newContent = lines.join("\n")

      await azure.createBranch({ branchName })

      commitSha = await azure.createCommit({
        branch: branchName,
        filePath: task.file_path,
        content: newContent,
        message: `fix: ${task.title}\n\nUpdates CNPJ format on line ${task.line_number} to alphanumeric 18-character format.`,
      })

      if (method === "pull_request") {
        const prDescription = `## Auto-generated fix for CNPJ format\n\n**Task:** ${task.title}\n**File:** \`${task.file_path}\`\n**Line:** ${task.line_number}\n\n### Changes\n\n\`\`\`diff\n- ${task.code_current}\n+ ${task.code_suggested}\n\`\`\`\n\n---\n\nThis PR was automatically generated by the CNPJ Analysis System.`

        const pr = await azure.createPullRequest({
          title: `Fix: ${task.title}`,
          description: prDescription,
          sourceBranch: branchName,
          targetBranch: "main",
        })

        prNumber = pr.number
        prUrl = pr.url
      }
    } else {
      throw new Error(`Provider ${task.repository.provider} not supported yet`)
    }

    await supabase
      .from("tasks")
      .update({
        pr_url: prUrl,
        pr_number: prNumber,
        pr_branch: branchName,
        pr_status: method === "pull_request" ? "open" : undefined,
        applied_at: new Date().toISOString(),
        applied_by: user_id,
        apply_method: method,
        status: method === "direct_commit" ? "concluido" : "em_progresso",
      })
      .eq("id", task.id)

    console.log(" Task updated with PR info")
    console.log(" Fix applied successfully!")

    return NextResponse.json({
      success: true,
      method,
      pr_url: prUrl,
      pr_number: prNumber,
      branch_name: branchName,
      commit_sha: commitSha,
    })
  } catch (error: any) {
    console.error(" Error applying fix:", error)
    return NextResponse.json({ error: error.message || "Internal server error" }, { status: 500 })
  }
}
